# Welcome to Jekyll!
#

# Site settings
title: Trash City
description: |
  How does moving week impact the quality of life in Boston?
site.owner: Jim Haddadin
first_published: 2017
email: jhaddadin@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
repository: trashcity/jhaddadin.github.io
social:
  twitter: https://twitter.com/JimHaddadin
  github: https://github.com/jhaddadin
  linkedin-square: https://linkedin.com/in/jimhaddadin
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
